import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/user/header";
import CommonLayout from "@/components/common/common-layout";
import authAxios from '@/lib/authAxios'; // This runs the interceptor setup

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         
        {/* <div className="min-h-screen bg-white"> */}
          {/* <Header/>
          <main>{children}</main> */}

          <CommonLayout>{children}</CommonLayout>
          <Toaster />

        {/* </div> */}
      </body>
    </html>
  );
}
